services:
  - type: web
    name: eirs-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && cd server && npm install && cd ../client && npm install && cd .. && npm run build
    startCommand: node api/index.js
    envVars:
      - key: MONGO_URL
        scope: build,runtime
        value: mongodb+srv://rijusarkar9640:hgtWfu3E5SqFxZXh@cluster0.6bdcvde.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        scope: build,runtime
        value: Secret
      - key: NODE_ENV
        scope: build,runtime
        value: production
      - key: EMAIL_USER
        scope: build,runtime
        value: technologyeirs@gmail.com
      - key: EMAIL_PASSWORD
        scope: build,runtime
        value: alvkfppkptaptzta
      - key: FRONTEND_URL
        scope: build,runtime
        value: https://eirs.vercel.app
      - key: RAZORPAY_KEY_ID
        scope: build,runtime
        value: rzp_live_SK2al1KdtZ4MA3
      - key: RAZORPAY_KEY_SECRET
        scope: build,runtime
        value: 2lyRlnz8Erd6EkbOUIvHTONp
      - key: RAZORPAY_WEBHOOK_SECRET
        scope: build,runtime
        value: ""
      - key: TWILIO_ACCOUNT_SID
        scope: build,runtime
        sync: false
      - key: TWILIO_AUTH_TOKEN
        scope: build,runtime
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        scope: build,runtime
        sync: false
      - key: PHONE_JWT_SECRET
        scope: build,runtime
        sync: false
